### ISSUE TITLE
Effect of relative number of RNA and ATAC cells

### ISSUE THREAD

**Issue by jindalk** [buenrostrolab/stimATAC_analyses_code#1]
Hi, great job developing this tool for integrative analysis!
I noticed in the paper that most datasets had far more ATAC cells than RNA cells. Since cells from the modality with fewer cells are resampled during optimal matching, do you know how the relative number of RNA and ATAC cells affects matching and DORC inference? Is there any data on how DORC inference changes (if it does) when relative number of RNA and ATAC cells in the dataset are changed, especially in cases where RNA cells >> ATAC cells.

Thanks

**Comment by vkartha** [comment]
Hi! Thank you for your interest! We have in fact not formally tested the effect of relative abundances of cells from either assay.  Since the optmatch pairing is reliant on the co-embedding of ATAC/RNA cells, I imagine this imbalance will not depend on whether the number of cells for ATAC is >>> RNA (or the other way around), but rather whether the system and platform allows you to sample evenly (in terms of the variance explained by the top variable RNA genes and ATAC gene scores) across different cell states / types, in which case it won't matter either direction. The DORC calling, as such, won't be sensitive to it since it uses Spearman correlations across all paired cells, but this is indeed something we are actively looking into (i.e. the downstream effects of assay bias). What we do know is that it uses more of your actual data, and is hence more likely to sample co-variance than a more greedy matching approach which would match the same cell way more frequently
